services:
  - type: web
    name: weather-pipeline-web
    runtime: docker
    repo: https://github.com/MpiloG29/Weather-Data-Pipeline-Project-
    branch: master
    dockerfilePath: ./Dockerfile.web
    envVars:
      - key: DATABASE_URL
        value: sqlite:///data/weather_data.db
    disk:
      name: weather-data
      mountPath: /app/data
      sizeGB: 1